# Site Settings
title: MadPlayðŸš€
description: "Curiosity and Experience never get old."
url: "https://madplay.github.io"
baseurl: ""
g-analytics: "UA-111002457-1"
ga4_measurement_id: "G-YH3W70BTL1"

# Language Settings
languages: [ "ko", "en" ]
default_lang: "ko"
lang_names:
  ko: "í•œêµ­ì–´"
  en: "English"

# Time Zone
timezone: Asia/Seoul

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: /post/:title

# Kramdown Settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Plugins (GitHub Pages í˜¸í™˜)
plugins:
  - jekyll-paginate
  - jekyll-feed

# Pagination
paginate: 10
paginate_path: /page:num

# Exclude
exclude:
  - README.md
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - assets/bower_components
